# Generated by Django 3.2.7 on 2021-11-12 08:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', tinymce.models.HTMLField(verbose_name='博客内容')),
                ('img', models.ImageField(upload_to='img/news')),
                ('add_date', models.DateTimeField(default=datetime.datetime(2021, 11, 12, 8, 41, 9, 714322, tzinfo=utc), verbose_name='保存日期')),
                ('mod_date', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
            ],
            options={
                'verbose_name': '博客表',
                'verbose_name_plural': '博客表',
                'db_table': 'news',
            },
        ),
    ]
