# Generated by Django 3.2.7 on 2021-11-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogs_add_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='description',
            field=models.CharField(default='', max_length=1024, verbose_name='文章描述'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='keywords',
            field=models.CharField(default='', max_length=1024, verbose_name='关键词'),
        ),
    ]
