# Generated by Django 3.2.7 on 2021-11-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211112_1758'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='blogs',
            table='blog',
        ),
    ]
