# Generated by Django 3.2.7 on 2021-11-17 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.CharField(default='', max_length=128, verbose_name='作者'),
        ),
    ]
